### ISSUE TITLE
Lips section not in v1.06(2)

### ISSUE THREAD

**Issue by Coletti1985** [Love-My-Delta-Inc/LMD_iOS#11]
Only Forehead Lines and Glabellar Lines ("11" Lines) appear in the newest version being prepared for release.

**Comment by jkellyLMD** [comment]
I'll go ahead and close this one for now. I believe the treatment info is instead being prioritized and then we'll have those included. 

Once we have a new version where it is expected to be in, if it isn't feel free to submit new issue.
