### ISSUE TITLE
B5 - Privacy Policy - Access to Specific Information and Data Portability Rights section

### ISSUE THREAD

**Issue by Coletti1985** [Love-My-Delta-Inc/LMD_iOS#14]
Underlining missing for text, "Exercising Access, Data Portability, and Deletion Rights" - specifically under, "Access to Specific Information and Data Portability Rights," section.
![IMG_4069](https://user-images.githubusercontent.com/93683591/160315310-b822c745-f114-4311-ab4e-d4fe5c4b56c0.jpg)

**Comment by jkellyLMD** [comment]
Fixed the version that David uses for the underlining. Removed other bold-face font I saw in the privacy policy. Please use this for future testing. 

@Coletti1985 
@Semeon-Tester 

[LMD Privacy Policy (Patients).DOCX](https://github.com/Love-My-Delta-Inc/LMD_iOS/files/8364767/LMD.Privacy.Policy.Patients.DOCX)

**Comment by Coletti1985** [comment]
@jkellyLMD - Does this comment mean that the app now includes the proper underlining?

**Comment by jkellyLMD** [comment]
@Coletti1985 The next version of the app should now include the proper underlining. Once the next version of the app comes out feel free to close this issue if it has been fixed.

**Comment by Coletti1985** [comment]
6APR2022 - Looks good!
