### ISSUE TITLE
B6 - Terms of Use - Title Bolding and Missing Text

### ISSUE THREAD

**Issue by Coletti1985** [Love-My-Delta-Inc/LMD_iOS#15]
Title not bolded.
Missing text.
1. Showing lack of bolding.
2. Showing text which is missing found in approved content but not in app.  [Red box].
![IMG_4071](https://user-images.githubusercontent.com/93683591/160315466-e7e55415-0cf6-4f41-979f-37438f630340.jpg)
![LMD_B6_MissingText_27MAR2022](https://user-images.githubusercontent.com/93683591/160315662-854be0c3-fd77-470d-8f90-d579d53aefdf.png)

**Comment by jkellyLMD** [comment]
Removed bold-face font from approved content. Please use attached for future testing. 
Edited the version David uses to include the missing content. 

@Coletti1985 
@Semeon-Tester 

[LoveMyDelta Application and Website Terms of Use.DOCX](https://github.com/Love-My-Delta-Inc/LMD_iOS/files/8364797/LoveMyDelta.Application.and.Website.Terms.of.Use.DOCX)

**Comment by Coletti1985** [comment]
@jkellyLMD - So the app should now _include_ the missing content, or should both be withoug?

**Comment by jkellyLMD** [comment]
@Coletti1985 The next version of the app should now include the missing content. Previously I think it was being included in the last bullet point instead of being a stand alone sentence. 

But it _should_ be there, yes.

**Comment by Coletti1985** [comment]
6APR2022 - Looks good!
