### ISSUE TITLE
B7 - Survey Agreement - Bolding, Formatting, and Mismatch Numbering

### ISSUE THREAD

**Issue by Coletti1985** [Love-My-Delta-Inc/LMD_iOS#16]
Whole Document:  Bolding not applied where stated in approved content.
2nd Title:  Not centered.
From 5 onwards:  Numbering different between app and approved content.

Bolding/2nd Title Format:  Github Screenshot 1
Mismatch Numbering:  Github Screenshot 2, (Actually starts at item before screenshot).

![IMG_4072](https://user-images.githubusercontent.com/93683591/160315825-8c4a5ab6-3ef4-47ad-a206-86c1253ea4a5.jpg)
![IMG_4073](https://user-images.githubusercontent.com/93683591/160315829-94b1292b-0d47-4bf3-ae8e-436e0394c63b.jpg)

**Comment by jkellyLMD** [comment]
On the bolding: we actually don't own the "bold" type license for this font so we can't apply bold fonts right now on the app with the font we use. (It was hard to convince Jim to buy the font at all so we had to just get the normal font.) So if you can make a change to address that in the test bed it would be great. 

On the numbering, I'll take a look and see if I can send David a corrected version to use.

**Comment by jkellyLMD** [comment]
@Coletti1985 I can't tell where the numbering is off, the screenshot is very small, but it seems like it's around #5 - Reporting Non-Permitted Use.... #6 - Availability of Internal Practices... and #7 - Access to and Amendment of PHI.
If I compare the HTML version to the word document I sent you guys I can't figure out the difference. 

Here is a version of the word doc though, with the bolding removed.  Please use this for further testing and if the numbering issue wasn't a mistake, let me know with a little more detail please. 
@Semeon-Tester 

[LMD - Survey Participant Agreement.DOCX](https://github.com/Love-My-Delta-Inc/LMD_iOS/files/8364877/LMD.-.Survey.Participant.Agreement.DOCX)

**Comment by Coletti1985** [comment]
@jkellyLMD - Oh, my bad.  Didn't realize the images were so small and blurry.  The issue is that on the app, the numbering jumps to 17, 18, 19, etc. after 5.

**Comment by Coletti1985** [comment]
Noted on the bolding on this one.

**Comment by jkellyLMD** [comment]
![IMG_1DF540BE4869-2](https://user-images.githubusercontent.com/64428109/160620217-ab3e4260-6dd0-452b-8ebd-b92255995db2.jpeg)
![IMG_1DF540BE4869-1](https://user-images.githubusercontent.com/64428109/160620223-209be5db-265d-4570-8fc4-214052a87713.jpeg)


I'm not seeing that issue on the version I'm using, screenshots pasted. Are you sure this is still a bug on the app?

**Comment by Coletti1985** [comment]
6APR2022 - Looks good now!
