### ISSUE TITLE
27OCT:  4.  Content appears to be cut off after the word, "thus."

### ISSUE THREAD

**Issue by Coletti1985** [Love-My-Delta-Inc/LMD_iOS#4]
This is a failed test case from the first round [27OCT2021] testing spreadsheet.

4.  Content appears to be cut off after the word, "thus." on the FOREHEAD LINES screen.

Was not corrected in the newest build (1.12).

**Comment by Coletti1985** [comment]
6JAN2022 - Issue not yet resolved.

**Comment by dspencer8192** [comment]
Can you add a pic of this?

**Comment by Coletti1985** [comment]
It's on the Excel, but attached here as well.
![ForeheadLines](https://user-images.githubusercontent.com/93683591/148457366-5f8a2763-c8c8-4b74-a9dd-93493d930007.png)

**Comment by dspencer8192** [comment]
Interesting, what phone are you using?

**Comment by Coletti1985** [comment]
The iPhone 8.

Best,
Mike Coletti
(415) 589-0019
***@***.***

**Comment by dspencer8192** [comment]
Thanks!

**Comment by Coletti1985** [comment]
Issue has been resolved!
